Repository project-raidho/raidho_FE, pull requests merged in 2022-10, with the labels that each got.

#400 [FEAT] 마이페이지 슬라이더 적용
  src/components/myProfile/MyMeetingList.jsx
  src/components/myProfile/MyPostList.jsx
Labels: 🏆 기능구현

#402 [FEAT] 검색 버튼으로 가능하게 설정&검색어 입력여부에 따른 오류모달, 페이지 이동시 스크롤 상단이동 설정
  src/components/header/search/SearchContainer.jsx
  src/components/searchTag/SearchTagPost.jsx
  src/global/GlobalLayout.jsx
  src/redux/modules/searchSlice.js
  src/shared/Router.jsx
Labels: 🐞오류, 🏆 기능구현

#403 [CD] 모집 카드 글자수에 따른 스타일 적용 및 글자수 제한, 검색기능 보완, 페이지 이동시 스크롤 상단이동
  src/components/chatting/Chat.jsx
  src/components/chatting/ChatName.jsx
  src/components/chatting/ChattingRoom.jsx
  src/components/chatting/Message.jsx
  src/components/chatting/MessageList.jsx
  src/components/chatting/MessageWrite.jsx
  src/components/createMeeting/MeetingLocationSearch.jsx
  src/components/header/search/SearchContainer.jsx
  src/components/meetingList/MeetingListCard.jsx
  src/components/meetingList/MeetingListContainer.jsx
  src/components/myProfile/MyMeetingList.jsx
  src/components/myProfile/MyPostList.jsx
  src/components/postDetail/PostDetailContainer.jsx
  src/components/postDetail/PostDetailLike.jsx
  src/components/postDetail/comment/AddCommentForm.jsx
  src/components/postDetail/comment/CommentsList.jsx
  src/components/searchTag/SearchTagPost.jsx
  src/elements/ContentTextArea.jsx
  src/global/GlobalLayout.jsx
  src/redux/modules/searchSlice.js
  src/shared/Router.jsx
Labels: 🎬 배포

#404 [FIX] 게시글 상세 태그 많은 경우 화면 깨지현상 해결
  src/components/postDetail/PostDetailTagList.jsx
Labels: 🐞오류

#405 [CD] 게시글 상세 태그 많은 경우 화면 깨지현상 해결
  src/components/postDetail/PostDetailTagList.jsx
Labels: 🎬 배포

#406 [FIX] 태그 입력개수 제한, 태그 많아지는 경우 화면 깨짐 현상 해결
  src/components/meetingList/MeetingListCard.jsx
  src/components/myProfile/MyProfileContainer.jsx
  src/elements/TagInput.jsx
Labels: 🐞오류, 🏆 기능구현, ⭐ 스타일

#407 [FIX] 태그 입력개수 제한, 태그 많아지는 경우 화면 깨짐 현상 해결
  src/components/meetingList/MeetingListCard.jsx
  src/components/myProfile/MyProfileContainer.jsx
  src/elements/TagInput.jsx
Labels: 🎬 배포

#408 [FEAT] 태그 제한, 등록시 모달창 설정
  src/components/createMeeting/CreateMeetingContainer.jsx
  src/components/createPost/CreatePostContainer.jsx
  src/components/updatePost/UpdatePostContainer.jsx
  src/components/updatePost/UpdatePostTags.jsx
  src/elements/TagInput.jsx
Labels: 🐞오류, 🏆 기능구현

#409 [CD] 태그 제한, 등록시 모달창 설정
  src/components/createMeeting/CreateMeetingContainer.jsx
  src/components/createPost/CreatePostContainer.jsx
  src/components/updatePost/UpdatePostContainer.jsx
  src/components/updatePost/UpdatePostTags.jsx
  src/elements/TagInput.jsx
Labels: 🎬 배포

#410 [FIX] textarea 크기조절 방지
  src/components/createPost/CreatePostContainer.jsx
  src/elements/TagInput.jsx
  src/global/GlobalStyle.jsx
Labels: 🐞오류

#411 [CD] textarea 크기조절 방지
  src/components/createPost/CreatePostContainer.jsx
  src/elements/TagInput.jsx
  src/global/GlobalStyle.jsx
Labels: 🎬 배포

#412 [FIX] 아이폰 날짜 계산 오류 해결
  src/components/meetingList/MeetingListCard.jsx
  src/components/postDetail/comment/Comment.jsx
Labels: 🐞오류

#413 [CD] 아이폰 날짜 NaN 오류 해결
  src/components/meetingList/MeetingListCard.jsx
  src/components/postDetail/comment/Comment.jsx
Labels: 🎬 배포

#414 [FIX] 주소입력하면 튕기는 오류 해결
  src/components/createMeeting/CreateMeetingContainer.jsx
Labels: 🐞오류

#416 [FEAT] 내용 내려쓰기 화면 출력 처리
  src/components/meetingList/MeetingListCard.jsx
  src/components/postDetail/PostDetailContainer.jsx
Labels: 🏆 기능구현, ⭐ 스타일

#417 [CD] 내용 내려쓰기 화면 출력 처리
  src/components/meetingList/MeetingListCard.jsx
  src/components/postDetail/PostDetailContainer.jsx
Labels: 🎬 배포

#418 [FEAT] 메인, 글로벌 타입스크립트 변환, 리덕스 타입스크립트 변환중
  .vscode/settings.json
  package.json
  src/App.tsx
  src/components/login/FacebookLogin.jsx
  src/components/login/KakaoLogin.tsx
  src/components/login/LoginContainer.tsx
  src/components/login/NaverLogin.jsx
  src/components/main/IntroTutorial.tsx
  src/components/main/MainBanner.tsx
  src/components/main/MainContainer.tsx
  src/components/main/MainPostCard.tsx
  src/components/main/MainPostList.tsx
  src/elements/Type.tsx
  src/global/AppLayout.jsx
  src/global/AppLayout.tsx
  src/global/GlobalFooter.tsx
  src/global/GlobalHeader.jsx
  src/global/GlobalLayout.tsx
  src/global/GlobalStyle.tsx
  src/global/globalModal/AlertModal.tsx
  src/global/globalModal/CofirmModal.tsx
  src/global/globalModal/Modal.tsx
  src/global/globalModal/Potal.jsx
  src/global/globalModal/Potal.tsx
  src/index.tsx
  src/pages/MainPage.tsx
  src/redux/modules/chat.js
  src/redux/modules/searchSlice.ts
  src/redux/modules/themeSlice.ts
  src/redux/store.ts
  src/shared/Router.tsx
  src/svg.d.ts
  tsconfig.json
  yarn.lock
Labels: 🏆 기능구현

#420 [FEAT] 라우터, 헤더, 리덕스 타입스크립트 변환
  package.json
  src/components/header/HeaderContainer.tsx
  src/components/header/HeaderRightMenu.tsx
  src/components/header/search/SearchContainer.tsx
  src/components/header/toggle/ToggleBox.tsx
  src/components/login/KakaoLogin.tsx
  src/components/main/IntroTutorial.tsx
  src/components/main/MainPostCard.tsx
  src/elements/HeartButton.tsx
  src/elements/Input.tsx
  src/global/globalModal/AlertModal.tsx
  src/redux/modules/searchSlice.ts
  src/redux/modules/themeSlice.ts
  src/redux/store.ts
  src/shared/KaKaoOauth.jsx
  src/shared/Router.tsx
  yarn.lock
Labels: 🏆 기능구현

#423 [FEAT] 게시글 등록, 미팅리스트, 검색상세 타입스크립트 변환
  package.json
  src/components/createPost/CreatePostContainer.tsx
  src/components/createPost/CreatePostContent.jsx
  src/components/createPost/CreatePostImage.tsx
  src/components/createPost/CreatePostImageCrop.tsx
  src/components/header/search/SearchContainer.tsx
  src/components/login/LoginContainer.tsx
  src/components/main/MainPostCard.jsx
  src/components/main/MainPostCard.tsx
  src/components/meetingList/MeetingListCard.tsx
  src/components/meetingList/MeetingListContainer.tsx
  src/components/myProfile/MyProfileContainer.tsx
  src/components/myProfile/UpdateMyProfile.tsx
  src/components/searchTag/SearchAlert.tsx
  src/components/searchTag/SearchTagContainer.tsx
  src/components/searchTag/SearchTagMeeting.jsx
  src/components/searchTag/SearchTagMeeting.tsx
  src/components/searchTag/SearchTagPost.jsx
  src/components/searchTag/SearchTagPost.tsx
  src/components/updatePost/UpdatePostContent.jsx
  src/components/updatePost/UpdatePostImage.jsx
  src/elements/Button.tsx
  src/elements/Input.tsx
  src/elements/Type.tsx
  src/pages/ChattingPage.tsx
  src/pages/CreateMeetingPage.tsx
  src/pages/CreatePostPage.tsx
  src/pages/MeetingListPage.tsx
  src/pages/MyProfilePage.tsx
  src/pages/NotFound.tsx
  src/pages/PostDetailPage.tsx
  src/pages/SearchTagPage.tsx
  src/pages/UpdateMeetingPage.tsx
  src/pages/UpdatePostPage.tsx
  src/shared/SocialOAuth.jsx
  src/shared/theme.js
  yarn.lock
Labels: 🏆 기능구현

#425 [DOCS] 리드미 문서 작성
  README.md
  docs/erd.png
  docs/logo160.jpg
  docs/tech.png
Labels: 📝 문서화

#430 [FEAT] 게시글수정 타입스크립트 변환, 게시글 수정 모듈태그 변환, 개발 소개 리드미작성
  README.md
  src/components/createPost/CreatePostContainer.tsx
  src/components/createPost/CreatePostImageCrop.tsx
  src/components/header/HeaderContainer.tsx
  src/components/header/HeaderRightMenu.tsx
  src/components/header/SearchContainer.tsx
  src/components/header/ToggleBox.tsx
  src/components/main/MainPostCard.tsx
  src/components/meetingList/MeetingListCard.tsx
  src/components/meetingList/MeetingListContainer.tsx
  src/components/myProfile/MyPostList.tsx
  src/components/postDetail/RelatedList.tsx
  src/components/searchTag/SearchTagMeeting.tsx
  src/components/updatePost/UpdatePostContainer.tsx
  src/components/updatePost/UpdatePostTags.jsx
  src/elements/Input.tsx
  src/elements/TagInput.tsx
  src/shared/theme.tsx
Labels: 🐞오류, 📝 문서화, 🏆 기능구현, 🛠 리팩토링

#434 [FEAT] 태그 특수문자 및 공백 입력 막기
  src/elements/TagInput.tsx
Labels: 🏆 기능구현

#439 [FIX] 최근검색어 오류 처리 변경
  src/components/main/IntroTutorial.tsx
  src/redux/modules/searchSlice.ts
Labels: 🐞오류, 🏆 기능구현

#440 [CD] 최근검색어 오류처리 변경
  src/components/main/IntroTutorial.tsx
  src/redux/modules/searchSlice.ts
Labels: 🎬 배포

#441 [FEAT] 기본 파일 타입스크립트 변환
  src/App.test.js
  src/App.test.tsx
  src/reportWebVitals.ts
  src/setupTests.ts
Labels: 🏆 기능구현

#442 [FIX] 메인 페이지 param->location으로 변경
  src/pages/MainPage.tsx
  src/pages/NotFound.tsx
  src/shared/Router.tsx
Labels: 🏆 기능구현

#445 [FEAT] 모바일 이미지 편집기능 수정
  src/components/createPost/CreatePostContainer.tsx
  src/components/createPost/CreatePostImage.tsx
  src/components/createPost/CreatePostImageCrop.tsx
Labels: 🏆 기능구현, ⭐ 스타일

#446 [FEAT] 로고, 인트로 가이드 수정
  public/favicon.ico
  src/assets/banner/bannerBg2.jpg
  src/assets/banner/bannerBg2.png
  src/assets/banner/intro2.jpeg
  src/assets/banner/intro3.jpeg
  src/assets/banner/intro4.jpeg
  src/assets/banner/intro5.jpeg
  src/assets/banner/intro6.jpeg
  src/assets/banner/intro7.jpeg
  src/assets/logo/logoDesktop.png
  src/assets/logo/logoMobile.png
  src/assets/raidhoLogo.svg
  src/assets/raidhoMobileLogo.svg
  src/assets/sampleProfile.png
  src/components/header/HeaderContainer.tsx
  src/components/login/LoginContainer.tsx
  src/components/main/IntroTutorial.tsx
  src/components/main/MainBanner.tsx
  src/components/meetingList/MeetingListContainer.tsx
Labels: 🏆 기능구현, ⭐ 스타일

#452 [FEAT] 사용안한 라이브러리 및 이미지 삭제, 채팅방 메시지 수정 외
  package.json
  src/assets/addPost.svg
  src/assets/emptyheart.png
  src/assets/facebook.svg
  src/assets/goChatting.svg
  src/assets/google.svg
  src/assets/header/add.svg
  src/assets/header/chat.svg
  src/assets/header/meeting.svg
  src/assets/header/post.svg
  src/assets/heart.png
  src/assets/naver.svg
  src/assets/naverlogo.png
  src/assets/notPrepare.svg
  src/assets/profile.svg
  src/assets/searchFocus.svg
  src/components/chatting/ChatList.tsx
  src/components/chatting/ChattingRoom.tsx
  src/components/chatting/MessageList.tsx
  src/components/chatting/NoRoom.tsx
  src/components/header/HeaderRightMenu.tsx
  src/components/header/SearchContainer.tsx
  src/components/myProfile/UpdateMyProfile.tsx
  src/elements/Input.tsx
  src/pages/MainPage.tsx
  yarn.lock
Labels: 🎬 배포

#453 [FEAT] 코드 수정
  src/components/header/SearchContainer.tsx
Labels: 🏆 기능구현

#456 [CD] 배너 s3이미지로 변경, 사용 안하는 코드 삭제
  public/index.html
  src/assets/banner/bannerBg1.png
  src/assets/banner/bannerBg2.jpg
  src/assets/banner/bannerContent1.png
  src/assets/banner/bannerContent2.png
  src/assets/banner/bannerMobile1.png
  src/assets/banner/bannerMobile2.png
  src/assets/banner/intro1.jpeg
  src/assets/banner/intro4.jpeg
  src/assets/banner/intro5.jpeg
  src/assets/banner/intro6.jpeg
  src/assets/banner/intro7.jpeg
  src/components/header/SearchContainer.tsx
  src/components/main/IntroTutorial.tsx
  src/components/main/MainBanner.tsx
  src/shared/SocialOAuth.tsx
Labels: 🎬 배포

#457 [FEAT] 마이페이지 유저이미지 리사이징추가, 간격조정, 웹폰트 최적화 외
  src/components/createPost/CreatePostImageCrop.tsx
  src/components/myProfile/MyPostList.tsx
  src/components/myProfile/UpdateMyProfile.tsx
  src/components/postDetail/PostDetailContainer.tsx
  src/components/postDetail/comment/AddCommentForm.tsx
  src/global/GlobalStyle.tsx
  src/pages/MainPage.tsx
Labels: 🏆 기능구현, ⭐ 스타일

#458 [CD] 마이페이지 유저이미지 리사이징추가, 간격조정, 웹폰트 최적화 외
  src/components/createPost/CreatePostImageCrop.tsx
  src/components/myProfile/MyPostList.tsx
  src/components/myProfile/UpdateMyProfile.tsx
  src/components/postDetail/PostDetailContainer.tsx
  src/components/postDetail/comment/AddCommentForm.tsx
  src/global/GlobalStyle.tsx
  src/pages/MainPage.tsx
Labels: 🎬 배포
