Repository project-raidho/raidho_FE, pull requests merged in 2022-08, with the labels that each got.

#1 [DOCS] pr 테스트용
  README.md
Labels: documentation

#15 [FIX] Error 해결
  src/components/createPost/CreatePostImage.jsx
Labels: bug

#23 [FEAT] Image Crop 기능 추가
  README.md
  package.json
  src/components/createPost/CreatePostImage.jsx
  src/components/createPost/CreatePostImageCrop.jsx
  src/elements/Button.jsx
  yarn.lock
Labels: enhancement

#27 [FEAT] 메인페이지 메뉴, masonry, 좋아요버튼 추가 #26
  public/index.html
  src/assets/emptyheart.png
  src/assets/heart.png
  src/components/login/FacebookLogin.jsx
  src/components/login/LoginContainer.jsx
  src/components/main/HeartButton.jsx
  src/components/main/MainMenu.jsx
  src/components/main/MainPostCard.jsx
  src/components/main/MainPostList.jsx
  src/components/main/postDetail/PostDetailContainer.jsx
  src/components/main/postDetail/PostDetailContent.jsx
  src/components/main/postDetail/PostDetailLike.jsx
  src/components/main/postDetail/PostDetailUser.jsx
  src/components/main/postDetail/postDetailImage.jsx
  src/elements/Button.jsx
  src/global/GlobalHeader.jsx
  src/pages/MainPage.jsx
Labels: 🏆enhancement

#29 [FEAT] 메인 masonry, 좋아요 기능 추가 / 게시글등록 이미지 편집 기능
  README.md
  package.json
  public/index.html
  src/assets/emptyheart.png
  src/assets/heart.png
  src/components/createPost/CreatePostImage.jsx
  src/components/createPost/CreatePostImageCrop.jsx
  src/components/login/FacebookLogin.jsx
  src/components/login/LoginContainer.jsx
  src/components/main/HeartButton.jsx
  src/components/main/MainMenu.jsx
  src/components/main/MainPostCard.jsx
  src/components/main/MainPostList.jsx
  src/components/main/postDetail/PostDetailContainer.jsx
  src/components/main/postDetail/PostDetailContent.jsx
  src/components/main/postDetail/PostDetailLike.jsx
  src/components/main/postDetail/PostDetailUser.jsx
  src/components/main/postDetail/postDetailImage.jsx
  src/elements/Button.jsx
  src/global/GlobalHeader.jsx
  src/pages/MainPage.jsx
  src/shared/KaKaoOauth.js
  yarn.lock
Labels: 🎬deploy

#31 [FEAT] 헤더 뷰 작업 (#30)
  src/assets/addPost.svg
  src/assets/goChatting.svg
  src/assets/raidhoLogo.svg
  src/assets/search.svg
  src/assets/searchFocus.svg
  src/components/createPost/CreatePostContent.jsx
  src/components/createPost/CreatePostImage.jsx
  src/components/createPost/CreatePostImageCrop.jsx
  src/components/header/search/SearchContainer.jsx
  src/elements/Button.jsx
  src/elements/Input.jsx
  src/global/GlobalHeader.jsx
  src/global/GlobalLayout.jsx
Labels: 🏆enhancement

#32 [FEAT] 헤더 뷰 작업 (#30)
  src/assets/addPost.svg
  src/assets/goChatting.svg
  src/assets/raidhoLogo.svg
  src/assets/search.svg
  src/assets/searchFocus.svg
  src/components/createPost/CreatePostContent.jsx
  src/components/createPost/CreatePostImage.jsx
  src/components/createPost/CreatePostImageCrop.jsx
  src/components/header/search/SearchContainer.jsx
  src/elements/Button.jsx
  src/elements/Input.jsx
  src/global/GlobalHeader.jsx
  src/global/GlobalLayout.jsx
Labels: 🏆enhancement
