Repository project-raidho/raidho_FE, pull requests merged in 2022-09, with the labels that each got.

#33 [FEAT] 헤더 뷰작업 및 서치 박스 상세보기 구현(#30)
  src/assets/sampleProfile.png
  src/components/header/search/SearchContainer.jsx
  src/elements/Button.jsx
  src/elements/Input.jsx
  src/global/GlobalHeader.jsx
  src/global/GlobalStyle.jsx
Labels: 🏆enhancement

#36 [FEAT] 메인 상세 페이지 작업, 헤더 작업 (#30 / #34)
  .gitignore
  package.json
  src/assets/profile.svg
  src/assets/sampleProfile.png
  src/components/header/search/SearchContainer.jsx
  src/components/main/HeartButton.jsx
  src/components/main/MainPostCard.jsx
  src/components/main/MainPostList.jsx
  src/components/main/postDetail/PostDetailContainer.jsx
  src/components/main/postDetail/PostDetailLike.jsx
  src/components/main/postDetail/PostDetailUser.jsx
  src/elements/Button.jsx
  src/elements/Input.jsx
  src/global/GlobalHeader.jsx
  src/global/GlobalStyle.jsx
  yarn.lock
Labels: 🎬deploy

#41 [FEAT] 상세페이지, 로그인 모달 구현 (#40 #34)
  src/components/login/FacebookLogin.jsx
  src/components/login/LoginContainer.jsx
  src/components/login/NaverLogin.jsx
  src/components/main/HeartButton.jsx
  src/components/main/MainPostCard.jsx
  src/components/main/postDetail/PostDetailContainer.jsx
  src/components/main/postDetail/PostDetailLike.jsx
  src/components/main/postDetail/PostDetailUser.jsx
  src/shared/KaKaoOauth.js
Labels: 🏆enhancement

#42 [FIX] warning 주석 처리
  src/components/main/postDetail/PostDetailLike.jsx
Labels: 🐞bug

#45 [FEAT] 마이페이지 유저 프로필 수정모달 연결 및 내 게시글 보기(#39)
  src/components/login/LoginContainer.jsx
  src/components/myProfile/MyPostList.jsx
  src/components/myProfile/MyProfileContainer.jsx
  src/components/myProfile/UpdateMyProfile.jsx
  src/global/globalModal/Modal.jsx
Labels: 🏆enhancement

#46 [CD] 마이페이지 뷰 구현
  src/components/login/LoginContainer.jsx
  src/components/myProfile/MyPostList.jsx
  src/components/myProfile/MyProfileContainer.jsx
  src/components/myProfile/UpdateMyProfile.jsx
  src/global/globalModal/Modal.jsx
Labels: 🎬deploy

#47 [CD] cloudFront 연결 및 https 설정 후 배포
  .github/workflows/raidho.yml
Labels: 🎬deploy

#64 [FEAT] 게시글 등록 태그 추가 삭제 기능
  README.md
  src/components/createPost/CreatePostContainer.jsx
  src/components/createPost/CreatePostContent.jsx
  src/components/createPost/CreatePostImage.jsx
  src/components/createPost/CreatePostImageCrop.jsx
  src/components/createPost/CreatePostTags.jsx
  src/elements/Button.jsx
  src/pages/CreatePostPage.jsx
Labels: 🏆 기능구현

#65 [FEAT] 채팅 추가, 소셜로그인 수정
  package.json
  src/assets/naverlogo.png
  src/components/chatting/Chat.jsx
  src/components/chatting/ChatList.jsx
  src/components/chatting/ChattingCard.jsx
  src/components/chatting/ChattingList.jsx
  src/components/chatting/ChattingRoom.jsx
  src/components/chatting/MessageList.jsx
  src/components/chatting/MessageWrite.jsx
  src/components/chatting/NoRoom.jsx
  src/components/login/FacebookLogin.jsx
  src/components/login/KakaoLogin.jsx
  src/components/login/LoginContainer.jsx
  src/components/login/NaverLogin.jsx
  src/components/main/postDetail/PostDetailContainer.jsx
  src/components/main/postDetail/postDetailImage.jsx
  src/elements/ChatInput.jsx
  src/elements/ChatName.jsx
  src/elements/Grid.jsx
  src/elements/Image.jsx
  src/elements/Message.jsx
  src/index.js
  src/pages/ChattingPage.jsx
  src/redux/modules/chat.js
  src/redux/modules/postSlice.js
  src/redux/modules/userSlice.js
  src/redux/store.js
  src/shared/KaKaoOauth.jsx
  src/shared/Request.jsx
  src/shared/Router.jsx
  src/shared/SocialOAuth.jsx
  src/shared/api.jsx
  yarn.lock
Labels: 🏆 기능구현

#66 [CD] 소셜로그인 수정, 채팅 기능추가, 게시글등록 태그 등록 및 삭제 기능
  README.md
  package.json
  src/assets/naverlogo.png
  src/components/chatting/Chat.jsx
  src/components/chatting/ChatList.jsx
  src/components/chatting/ChattingCard.jsx
  src/components/chatting/ChattingList.jsx
  src/components/chatting/ChattingRoom.jsx
  src/components/chatting/MessageList.jsx
  src/components/chatting/MessageWrite.jsx
  src/components/chatting/NoRoom.jsx
  src/components/createPost/CreatePostContainer.jsx
  src/components/createPost/CreatePostContent.jsx
  src/components/createPost/CreatePostImage.jsx
  src/components/createPost/CreatePostImageCrop.jsx
  src/components/createPost/CreatePostTags.jsx
  src/components/login/FacebookLogin.jsx
  src/components/login/KakaoLogin.jsx
  src/components/login/LoginContainer.jsx
  src/components/login/NaverLogin.jsx
  src/components/main/postDetail/PostDetailContainer.jsx
  src/components/main/postDetail/postDetailImage.jsx
  src/elements/Button.jsx
  src/elements/ChatInput.jsx
  src/elements/ChatName.jsx
  src/elements/Grid.jsx
  src/elements/Image.jsx
  src/elements/Message.jsx
  src/index.js
  src/pages/ChattingPage.jsx
  src/pages/CreatePostPage.jsx
  src/redux/modules/chat.js
  src/redux/modules/postSlice.js
  src/redux/modules/userSlice.js
  src/redux/store.js
  src/shared/KaKaoOauth.jsx
  src/shared/Request.jsx
  src/shared/Router.jsx
  src/shared/SocialOAuth.jsx
  src/shared/api.jsx
  yarn.lock
Labels: 🎬 배포

#70 [FEAT] 최근검색기록 로컬스토리지 저장 및 삭제, 태그 페이지 이동(#69) / readme 문서 수정
  README.md
  src/components/header/search/SearchContainer.jsx
  src/components/searchTag/SearchTagContainder.jsx
  src/elements/Button.jsx
  src/global/GlobalHeader.jsx
  src/pages/SearchTagPage.jsx
  src/shared/Router.jsx
Labels: 🏆 기능구현

#74 [CD] 오류 주석처리
  src/elements/ChatName.jsx
Labels: 🪨 주석

#77 [DOCS] Readme 개발 타임라인 작성
  README.md
  src/components/login/KakaoLogin.jsx
  src/global/GlobalLayout.jsx
  src/shared/KaKaoOauth.jsx
  src/shared/Router.jsx
  src/shared/SocialOAuth.jsx
Labels: 📝 문서화

#78 [FIX] git 파일 싱크 맞추기
  .github/workflows/raidho.yml
Labels: 🐞오류

#79 [FIX] yml 주석처리
  .github/workflows/raidho.yml
  src/components/login/KakaoLogin.jsx
  src/components/main/MainPostCard.jsx
  src/shared/Router.jsx
Labels: 🪨 주석

#80 [CD] yml 수정
  .github/workflows/raidho.yml
  README.md
  src/components/login/KakaoLogin.jsx
  src/components/main/MainPostCard.jsx
  src/global/GlobalLayout.jsx
  src/shared/KaKaoOauth.jsx
  src/shared/Router.jsx
  src/shared/SocialOAuth.jsx
Labels: 🎬 배포

#81 [FEAT] 로그인 연결
  src/components/login/KakaoLogin.jsx
Labels: 💦 테스트

#82 [CD] 카카오 로그인 연결 테스트
  src/components/login/KakaoLogin.jsx
Labels: 🎬 배포

#84 [CD] 오류 수정후 배포 테스트
  src/components/login/KakaoLogin.jsx
Labels: 🎬 배포

#85 [FIX] 환경변수 설정
  src/shared/SocialOAuth.jsx
Labels: 🐞오류

#87 [SETTING] env 환경변수 설정
  .env
  .github/workflows/raidho.yml
  .gitignore
  src/shared/SocialOAuth.jsx
Labels: 💦 테스트

#88 [CD] env 환경변수 설정
  .env
  .github/workflows/raidho.yml
  .gitignore
  src/shared/SocialOAuth.jsx
Labels: 🎬 배포

#89 [SETTING] env 환경변수 설정
  src/shared/SocialOAuth.jsx
Labels: 🐞오류

#90 [SETTING] env 환경변수 설정
  src/shared/SocialOAuth.jsx
Labels: 🎬 배포

#92 [FIX] 통신오류로 html 파일 코드 추가
  public/index.html
Labels: 🎬 배포

#93 [DOCS] Readme 9월 6일 개발타임라인 작성
  README.md
  src/components/login/KakaoLogin.jsx
  src/shared/SocialOAuth.jsx
Labels: 📝 문서화

#95 [FEAT] 모집방 개설 페이지 기능 추가
  .github/workflows/raidho.yml
  package.json
  src/components/createMeeting/CreateMeetingContainer.jsx
  src/components/createMeeting/TripLocationSelect.jsx
  src/components/login/KakaoLogin.jsx
  src/pages/CreateMeetingPage.jsx
  yarn.lock
Labels: 🏆 기능구현

#96 [FIX] 최근 검색기록 상세로 들어갔을때 작동안하는 현상 해결중
  public/index.html
  src/components/header/search/SearchContainer.jsx
  src/global/GlobalHeader.jsx
  src/pages/SearchTagPage.jsx
Labels: 🐞오류

#99 [FEAT] 최근검색기록 오류 해결 외 자잘자잘한 기능구현
  README.md
  src/components/createPost/CreatePostContainer.jsx
  src/components/createPost/CreatePostImage.jsx
  src/components/createPost/CreatePostImageCrop.jsx
  src/components/createPost/CreatePostTags.jsx
  src/components/header/search/SearchContainer.jsx
  src/components/login/FacebookLogin.jsx
  src/components/login/LoginContainer.jsx
  src/components/main/MainMenu.jsx
  src/components/main/postDetail/postDetailImage.jsx
  src/components/meetingList/MeetingListCard.jsx
  src/components/meetingList/MeetingListContainer.jsx
  src/elements/Button.jsx
  src/global/GlobalHeader.jsx
  src/pages/MeetingListPage.jsx
  src/pages/SearchTagPage.jsx
  src/redux/modules/searchSlice.js
  src/redux/modules/themeSlice.js
  src/redux/store.js
Labels: 🐞오류, 🏆 기능구현

#100 [FEAT] 모집방 개설 페이지 달력, 테마 기능 추가
  package.json
  src/components/createMeeting/Calender.jsx
  src/components/createMeeting/CreateMeetingContainer.jsx
  src/components/createMeeting/RoomclosedateBox.jsx
  src/components/createMeeting/ThemeSelect.jsx
  src/components/createMeeting/TripLocationSelect.jsx
  src/elements/Input.jsx
  src/pages/CreateMeetingPage.jsx
  yarn.lock
Labels: 🏆 기능구현

#101 [CD] 서버 통신 테스트
  README.md
  src/components/createMeeting/Calender.jsx
  src/components/createMeeting/RoomclosedateBox.jsx
  src/components/login/KakaoLogin.jsx
  src/components/meetingList/MeetingListContainer.jsx
  src/redux/modules/meetingSlice.js
  src/redux/store.js
Labels: 💦 테스트

#102 [CD] https 서버통신 테스트
  .github/workflows/raidho.yml
  README.md
  package.json
  public/index.html
  src/components/createMeeting/Calender.jsx
  src/components/createMeeting/CreateMeetingContainer.jsx
  src/components/createMeeting/RoomclosedateBox.jsx
  src/components/createMeeting/ThemeSelect.jsx
  src/components/createMeeting/TripLocationSelect.jsx
  src/components/createPost/CreatePostContainer.jsx
  src/components/createPost/CreatePostImage.jsx
  src/components/createPost/CreatePostImageCrop.jsx
  src/components/createPost/CreatePostTags.jsx
  src/components/header/search/SearchContainer.jsx
  src/components/login/FacebookLogin.jsx
  src/components/login/KakaoLogin.jsx
  src/components/login/LoginContainer.jsx
  src/components/main/MainMenu.jsx
  src/components/main/postDetail/postDetailImage.jsx
  src/components/meetingList/MeetingListCard.jsx
  src/components/meetingList/MeetingListContainer.jsx
  src/elements/Button.jsx
  src/elements/Input.jsx
  src/global/GlobalHeader.jsx
  src/pages/CreateMeetingPage.jsx
  src/pages/MeetingListPage.jsx
  src/pages/SearchTagPage.jsx
  src/redux/modules/meetingSlice.js
  src/redux/modules/searchSlice.js
  src/redux/modules/themeSlice.js
  src/redux/store.js
  src/shared/SocialOAuth.jsx
  yarn.lock
Labels: 🎬 배포

#103 [TEST] https서버통신
  src/components/meetingList/MeetingListCard.jsx
  src/components/meetingList/MeetingListContainer.jsx
Labels: 💦 테스트

#104 [TEST] https서버통신
  src/components/meetingList/MeetingListCard.jsx
  src/components/meetingList/MeetingListContainer.jsx
Labels: 🎬 배포

#105 [TEST] https 통신
  README.md
Labels: 💦 테스트

#113 [TEST] https test : 443
  README.md
Labels: 💦 테스트

#122 [STYLE] 모집방 개설 페이지 스타일 추가
  package.json
  public/index.html
  src/components/createMeeting/Calender.jsx
  src/components/createMeeting/CreateMeetingContainer.jsx
  src/components/createMeeting/CreateMeetingContent.jsx
  src/components/createMeeting/CreateMeetingImage.jsx
  src/components/createMeeting/KakaoMap.jsx
  src/components/createMeeting/MeetingLocationSearch.jsx
  src/components/createMeeting/RoomclosedateBox.jsx
  src/components/createMeeting/ThemeSelect.jsx
  src/components/createMeeting/TripLocationSelect.jsx
  src/components/createMeeting/TripPeriod.jsx
  yarn.lock
Labels: ⭐ 스타일

#123 [FEAT] 함께 여행가기 리스트 페이지 뷰작업 진행
  src/components/meetingList/MeetingListCard.jsx
  src/components/meetingList/MeetingListContainer.jsx
  src/redux/modules/meetingSlice.js
Labels: 🏆 기능구현

#124 [FEAT] 헤더 수정, 유저 프로필 편집 기능 완료, 게시글 등록 이미지 형변환
  README.md
  src/components/createPost/CreatePostContainer.jsx
  src/components/createPost/CreatePostContent.jsx
  src/components/createPost/CreatePostImage.jsx
  src/components/createPost/CreatePostImageCrop.jsx
  src/components/header/search/SearchContainer.jsx
  src/components/meetingList/MeetingList.jsx
  src/components/meetingList/MeetingListContainer.jsx
  src/components/myProfile/UpdateMyProfile.jsx
  src/global/GlobalHeader.jsx
  src/pages/ChattingPage.jsx
Labels: 🏆 기능구현

#127 [SETTING] typescript prettier setting 외
  .eslintrc.js
  .prettierrc
  package.json
  src/App.test.tsx
  src/App.tsx
  src/index.tsx
  tsconfig.json
  yarn.lock
Labels: 📝 문서화

#128 [FEAT] 타입스크립트 설정중...
  .eslintrc.js
  .yarn/releases/yarn-stable-temp.cjs
  src/App.tsx
  src/components/createPost/CreatePostContainer.tsx
  src/components/createPost/CreatePostContent.jsx
  src/components/createPost/CreatePostContent.tsx
  src/components/createPost/CreatePostImage.tsx
  src/components/createPost/CreatePostImageCrop.tsx
  src/components/createPost/CreatePostTags.tsx
  src/custom.d.ts
  src/elements/Button.tsx
  src/global/GlobalHeader.tsx
  src/global/GlobalLayout.jsx
  src/global/GlobalLayout.tsx
  src/global/GlobalStyle.tsx
  src/global/globalModal/Modal.tsx
  src/global/globalModal/Potal.jsx
  src/global/globalModal/Potal.tsx
  src/index.tsx
  src/pages/CreatePostPage.jsx
  src/pages/CreatePostPage.tsx
  tsconfig.json
Labels: 🏆 기능구현

#135 [FEAT] 게시글 수정페이지/헤더 다크앤라이트와 유저정보/마이페이지 유저정보 연결
  README.md
  src/App.js
  src/assets/defaultProfileImage.svg
  src/assets/iconDarkMode.svg
  src/assets/iconLightMode.svg
  src/components/createPost/CreatePostContainer.jsx
  src/components/createPost/CreatePostImageCrop.jsx
  src/components/header/search/SearchContainer.jsx
  src/components/login/KakaoLogin.jsx
  src/components/myProfile/UpdateMyProfile.jsx
  src/components/updatePost/UpdatePostContainer.jsx
  src/components/updatePost/UpdatePostContent.jsx
  src/components/updatePost/UpdatePostTags.jsx
  src/global/GlobalHeader.jsx
  src/global/GlobalLayout.jsx
  src/pages/UpdatePostPage.jsx
  src/redux/modules/searchSlice.js
  src/shared/Router.jsx
Labels: 🏆 기능구현

#137 [FEAT] 상세페이지 추가, 메인페이지 메뉴 기능 추가
  .env
  .gitignore
  src/components/createMeeting/CreateMeetingContainer.jsx
  src/components/createMeeting/MeetingLocationSearch.jsx
  src/components/createMeeting/ThemeSelect.jsx
  src/components/createMeeting/TripPeriod.jsx
  src/components/login/KakaoLogin.jsx
  src/components/main/MainMenu.jsx
  src/components/main/MainPostCard.jsx
  src/components/main/MainPostList.jsx
  src/components/main/postDetail/PostDetailContainer.jsx
  src/components/main/postDetail/PostDetailContent.jsx
  src/components/main/postDetail/PostDetailLike.jsx
  src/components/main/postDetail/postDetailImage.jsx
  src/components/postDetail/PostDetailContainer.jsx
  src/components/postDetail/PostDetailLike.jsx
  src/components/postDetail/PostDetailUser.jsx
  src/components/postDetail/postDetailImage.jsx
  src/index.js
  src/pages/CreateMeetingPage.jsx
  src/pages/PostDetailPage.jsx
  src/shared/Router.jsx
  src/shared/SocialOAuth.jsx
Labels: 🏆 기능구현

#138 [FEAT&ERROR] 게시글 수정 서버 전송 세팅, 헤더 수정 뷰작업, 게시글 등록 이미지 등록 에러 해결중
  src/components/createPost/CreatePostContainer.jsx
  src/components/header/search/SearchContainer.jsx
  src/components/header/search/SearchTag.jsx
  src/components/header/search/SearchTagList.jsx
  src/components/main/MainPostCard.jsx
  src/components/main/MainPostList.jsx
  src/components/searchTag/SearchTagContainder.jsx
  src/components/updatePost/UpdatePostContainer.jsx
  src/redux/modules/postSlice.js
  src/shared/Router.jsx
Labels: 🐞오류, 🏆 기능구현, ⭐ 스타일

#139 [STYLE] 채팅페이지 스타일 변경
  .gitignore
  src/components/chatting/Chat.jsx
  src/components/chatting/ChatList.jsx
  src/components/chatting/ChatName.jsx
  src/components/chatting/ChattingContainer.jsx
  src/components/chatting/ChattingRoom.jsx
  src/components/chatting/Message.jsx
  src/components/chatting/MessageList.jsx
  src/components/chatting/MessageWrite.jsx
  src/components/createPost/CreatePostContainer.jsx
  src/components/main/MainPostCard.jsx
  src/components/postDetail/postDetailImage.jsx
  src/elements/ChatInput.jsx
  src/elements/Message.jsx
  src/pages/ChattingPage.jsx
Labels: ⭐ 스타일

#140 [FEAT] 태그 중복체크 기능구현 및 태그 유효성검사 기능구현
  src/components/createPost/CreatePostContainer.jsx
  src/components/createPost/CreatePostContent.jsx
  src/components/createPost/CreatePostImage.jsx
  src/components/createPost/CreatePostImageCrop.jsx
  src/components/createPost/CreatePostTags.jsx
  src/components/meetingList/MeetingListCard.jsx
  src/components/meetingList/MeetingListContainer.jsx
  src/components/updatePost/UpdatePostContainer.jsx
  src/elements/Button.jsx
  src/redux/modules/themeSlice.js
  src/shared/Router.jsx
Labels: 🏆 기능구현

#146 [REFACTORY] axios 인스턴스
  src/assets/fileIcon.svg
  src/components/chatting/Chat.jsx
  src/components/chatting/ChatList.jsx
  src/components/chatting/ChatName.jsx
  src/components/chatting/ChattingRoom.jsx
  src/components/chatting/Message.jsx
  src/components/chatting/MessageList.jsx
  src/components/chatting/MessageWrite.jsx
  src/components/chatting/NoRoom.jsx
  src/components/createMeeting/CreateMeetingContainer.jsx
  src/components/createMeeting/MeetingLocationSearch.jsx
  src/components/createMeeting/RoomclosedateBox.jsx
  src/components/createMeeting/TripPeriod.jsx
  src/components/createPost/CreatePostContainer.jsx
  src/components/login/KakaoLogin.jsx
  src/components/main/MainPostCard.jsx
  src/components/postDetail/PostDetailContainer.jsx
  src/components/postDetail/PostDetailLike.jsx
  src/components/postDetail/PostDetailUser.jsx
  src/components/postDetail/postDetailImage.jsx
  src/components/updatePost/UpdatePostContainer.jsx
  src/redux/modules/chat.js
  src/shared/Router.jsx
  src/shared/api.jsx
Labels: 🛠 리팩토링

#147 [DEPLOY] axios 인스턴스 추가
  src/assets/fileIcon.svg
  src/components/chatting/Chat.jsx
  src/components/chatting/ChatList.jsx
  src/components/chatting/ChatName.jsx
  src/components/chatting/ChattingRoom.jsx
  src/components/chatting/Message.jsx
  src/components/chatting/MessageList.jsx
  src/components/chatting/MessageWrite.jsx
  src/components/chatting/NoRoom.jsx
  src/components/createMeeting/CreateMeetingContainer.jsx
  src/components/createMeeting/MeetingLocationSearch.jsx
  src/components/createMeeting/RoomclosedateBox.jsx
  src/components/createMeeting/TripPeriod.jsx
  src/components/createPost/CreatePostContainer.jsx
  src/components/login/KakaoLogin.jsx
  src/components/main/MainPostCard.jsx
  src/components/postDetail/PostDetailContainer.jsx
  src/components/postDetail/PostDetailLike.jsx
  src/components/postDetail/PostDetailUser.jsx
  src/components/postDetail/postDetailImage.jsx
  src/components/updatePost/UpdatePostContainer.jsx
  src/redux/modules/chat.js
  src/shared/Router.jsx
  src/shared/api.jsx
Labels: 🎬 배포

#148 [FEAT] 게시글 등록 레이아웃 수정
  src/components/createPost/CreatePostContainer.jsx
  src/components/createPost/CreatePostContent.jsx
  src/components/createPost/CreatePostImage.jsx
  src/components/createPost/CreatePostImageCrop.jsx
  src/components/postDetail/PostDetailContainer.jsx
  src/global/GlobalHeader.jsx
Labels: 🏆 기능구현, ⭐ 스타일, 🎬 배포

#149 [CD] 게시글 등록 레이아웃 수정, axios 인스턴스, 에러해결
  src/components/createPost/CreatePostContainer.jsx
  src/components/createPost/CreatePostContent.jsx
  src/components/createPost/CreatePostImage.jsx
  src/components/createPost/CreatePostImageCrop.jsx
  src/components/postDetail/PostDetailContainer.jsx
  src/global/GlobalHeader.jsx
Labels: 🏆 기능구현, ⭐ 스타일, 🛠 리팩토링, 🎬 배포

#151 [CD] 디테일 이미지 에러 수정
  src/components/postDetail/PostDetailContainer.jsx
  src/components/updatePost/UpdatePostContainer.jsx
Labels: 🎬 배포

#153 [CD] 디테일이미지 대문자로 변환
  src/components/postDetail/PostDetailContainer.jsx
  src/components/updatePost/UpdatePostContainer.jsx
Labels: 🎬 배포

#155 [CD] 파일이름변경
  src/components/postDetail/PostDetailContainer.jsx
  src/components/postDetail/PostDetailImg.jsx
  src/components/updatePost/UpdatePostContainer.jsx
Labels: 🎬 배포

#158 [FIX] api 수정
  src/components/createPost/CreatePostContainer.jsx
  src/shared/api.jsx
Labels: 💦 테스트

#159 [CD] 인스턴스 오류
  src/components/createPost/CreatePostContainer.jsx
  src/shared/api.jsx
Labels: 🎬 배포

#164 [STYLE] 헤더 스타일 변경
  src/components/header/search/SearchContainer.jsx
  src/elements/Input.jsx
  src/global/GlobalHeader.jsx
  src/global/GlobalStyle.jsx
  src/pages/ChattingPage.jsx
Labels: ⭐ 스타일

#167 [CD] 프로필 수정, 좋아요 서버 연결, 헤더 스타일 변경
  src/components/chatting/ChattingRoom.jsx
  src/components/header/search/SearchContainer.jsx
  src/components/main/MainMenu.jsx
  src/components/main/MainPostCard.jsx
  src/elements/Button.jsx
  src/elements/Input.jsx
  src/global/GlobalHeader.jsx
  src/global/GlobalStyle.jsx
  src/pages/ChattingPage.jsx
Labels: 🏆 기능구현, ⭐ 스타일, 🎬 배포

#171 [CD] 서버 테스트
  src/components/main/MainMenu.jsx
  src/components/meetingList/MeetingListContainer.jsx
Labels: 🎬 배포

#173 [CD] 서버 테스트
  src/components/main/MainMenu.jsx
Labels: 🎬 배포

#174 [FEAT] 모집 리스트 서버 연동 설정
  src/components/meetingList/MeetingListContainer.jsx
Labels: 🏆 기능구현

#177 [FIX] 좋아요 버튼에 토큰 추가
  src/components/main/MainPostCard.jsx
Labels: 🏆 기능구현

#178 [CD] 좋아요에 토큰 추가
  src/components/main/MainPostCard.jsx
Labels: 🎬 배포

#182 [FIX] 상세페이지 axios 수정
  src/components/main/MainMenu.jsx
  src/components/postDetail/PostDetailContainer.jsx
  src/components/postDetail/PostDetailLike.jsx
  src/components/postDetail/PostDetailUser.jsx
Labels: 🏆 기능구현

#183 [CD] 모집 리스트 날짜 계산하기, 상세페이지 axios 수정
  src/components/main/MainMenu.jsx
  src/components/meetingList/MeetingListCard.jsx
  src/components/postDetail/PostDetailContainer.jsx
  src/components/postDetail/PostDetailLike.jsx
  src/components/postDetail/PostDetailUser.jsx
  src/redux/modules/meetingSlice.js
Labels: 🎬 배포

#187 [CD] 상세페이지 좋아요 수정2
  src/components/postDetail/PostDetailContainer.jsx
  src/components/postDetail/PostDetailLike.jsx
Labels: 🎬 배포

#188 [FIX] 상세페이지 좋아요 수정
  src/components/postDetail/PostDetailContainer.jsx
  src/components/postDetail/PostDetailLike.jsx
Labels: 🐞오류

#193 [FIX]게시글 수정
  src/components/header/search/SearchContainer.jsx
  src/components/login/LoginContainer.jsx
  src/components/searchTag/SearchTagContainder.jsx
  src/components/updatePost/UpdatePostContainer.jsx
  src/components/updatePost/UpdatePostContent.jsx
  src/global/globalModal/Modal.jsx
Labels: 🐞오류

#195 [FIX] 게시글 수정
  src/components/updatePost/UpdatePostContainer.jsx
  src/components/updatePost/UpdatePostContent.jsx
  src/components/updatePost/UpdatePostTags.jsx
Labels: 🐞오류

#197 [FIX] 게시글 수정 오류 해결/package 로거 삭제
  package.json
  src/components/updatePost/UpdatePostContainer.jsx
  src/redux/store.js
  yarn.lock
Labels: 🐞오류

#199 [FIX]메인페이지 실시간 기본값으로 변경
  src/components/main/MainMenu.jsx
  src/components/postDetail/PostDetailUser.jsx
  src/components/updatePost/UpdatePostContainer.jsx
  src/components/updatePost/UpdatePostContent.jsx
Labels: 🏆 기능구현

#200 [FIX] 태그 #태그로 수정
  src/components/createPost/CreatePostContainer.jsx
  src/components/createPost/CreatePostTags.jsx
  src/components/updatePost/UpdatePostContainer.jsx
  src/components/updatePost/UpdatePostTags.jsx
Labels: 🏆 기능구현

#203 [FEAT] 좋아요 에러 처리
  src/components/createMeeting/CreateMeetingContainer.jsx
  src/components/main/MainMenu.jsx
  src/components/main/MainPostCard.jsx
  src/components/postDetail/PostDetailLike.jsx
  src/components/postDetail/PostDetailUser.jsx
Labels: 🏆 기능구현

#207 [FIX] 헤더 검색창 튀는 모습 해결, 검색상세페이지 레이아웃 변경
  src/components/header/search/SearchContainer.jsx
  src/components/searchTag/SearchTagContainder.jsx
  src/redux/modules/themeSlice.js
  src/shared/Router.jsx
Labels: 🐞오류, 🏆 기능구현

#209 [FEAT] 헤더 토글 닫기 기능 구현, 마이페이지 내 게시글 불러오기 세팅, 네브링크 에러해결
  src/components/meetingList/MeetingListContainer.jsx
  src/components/myProfile/MyPostList.jsx
  src/components/myProfile/MyProfileContainer.jsx
  src/components/searchTag/SearchTagContainder.jsx
  src/global/GlobalHeader.jsx
Labels: 🐞오류, 🏆 기능구현

#210 [CD] 헤더 토글 닫기 기능 구현, 마이페이지 내 게시글 불러오기 세팅, 네브링크 에러해결
  src/components/meetingList/MeetingListContainer.jsx
  src/components/myProfile/MyPostList.jsx
  src/components/myProfile/MyProfileContainer.jsx
  src/components/searchTag/SearchTagContainder.jsx
  src/global/GlobalHeader.jsx
Labels: 🎬 배포

#211 [FIX] 서버통신 테스트
  src/components/myProfile/MyPostList.jsx
  src/components/myProfile/MyProfileContainer.jsx
Labels: 🏆 기능구현

#213 [FIX] 마이페이지 내가 쓴 글 API 수정
  src/components/myProfile/MyPostList.jsx
Labels: 🐞오류

#214 [CD] 마이페이지 내가 쓴 글 API 수정
  src/components/myProfile/MyPostList.jsx
Labels: 🎬 배포

#215 [FEAT] 마이페이지 프로필 수정 스타일변경, 서버 전송 세팅(인스턴스 사용)
  src/components/myProfile/UpdateMyProfile.jsx
Labels: 🏆 기능구현, ⭐ 스타일

#216 [CD] 마이페이지 프로필 수정 스타일변경, 서버 전송 세팅(인스턴스 사용)
  src/components/myProfile/UpdateMyProfile.jsx
Labels: 🎬 배포

#217 [FIX] 스타일 수정
  src/components/createMeeting/CreateMeetingContainer.jsx
  src/components/createMeeting/ThemeSelect.jsx
  src/components/createMeeting/TripPeopleCount.jsx
  src/components/createPost/CreatePostContainer.jsx
  src/components/createPost/CreatePostImageCrop.jsx
  src/components/header/search/SearchContainer.jsx
  src/components/login/LoginContainer.jsx
  src/components/main/MainPostCard.jsx
  src/components/postDetail/PostDetailContainer.jsx
  src/components/postDetail/PostDetailImg.jsx
  src/components/postDetail/PostDetailLike.jsx
  src/components/postDetail/PostDetailUser.jsx
  src/elements/Button.jsx
  src/global/GlobalHeader.jsx
Labels: ⭐ 스타일

#218 [FEAT] 모집글 수정 페이지
  src/components/createMeeting/CreateMeetingContainer.jsx
  src/components/createMeeting/RoomCloseDateBox.jsx
  src/components/createMeeting/ThemeSelect.jsx
  src/components/createMeeting/TripPeopleCount.jsx
  src/components/createMeeting/UpdateMeetingContainer.jsx
  src/components/main/MainMenu.jsx
  src/components/main/MainPostCard.jsx
  src/components/postDetail/PostDetailContainer.jsx
  src/components/postDetail/PostDetailLike.jsx
  src/components/postDetail/PostDetailUser.jsx
  src/components/searchTag/SearchTagContainder.jsx
  src/pages/UpdateMeetingPage.jsx
  src/shared/Router.jsx
Labels: 🏆 기능구현, ⭐ 스타일

#219 [STYLE] 모집방 개설 페이지 아래 패딩값 추가
  src/components/createMeeting/CreateMeetingContainer.jsx
  src/components/createMeeting/ThemeSelect.jsx
  src/pages/CreateMeetingPage.jsx
Labels: ⭐ 스타일

#220 [CD] 모집글 수정페이지 추가, 전반적인 스타일 수정
  src/components/createMeeting/CreateMeetingContainer.jsx
  src/components/createMeeting/RoomCloseDateBox.jsx
  src/components/createMeeting/ThemeSelect.jsx
  src/components/createMeeting/TripPeopleCount.jsx
  src/components/createMeeting/UpdateMeetingContainer.jsx
  src/components/createPost/CreatePostContainer.jsx
  src/components/createPost/CreatePostImageCrop.jsx
  src/components/header/search/SearchContainer.jsx
  src/components/login/LoginContainer.jsx
  src/components/main/MainMenu.jsx
  src/components/main/MainPostCard.jsx
  src/components/postDetail/PostDetailContainer.jsx
  src/components/postDetail/PostDetailImg.jsx
  src/components/postDetail/PostDetailLike.jsx
  src/components/postDetail/PostDetailUser.jsx
  src/components/searchTag/SearchTagContainder.jsx
  src/elements/Button.jsx
  src/global/GlobalHeader.jsx
  src/pages/CreateMeetingPage.jsx
  src/pages/UpdateMeetingPage.jsx
  src/shared/Router.jsx
Labels: 🎬 배포

#222 [FIX] 상세페이지 이미지 스타일 수정
  src/components/createMeeting/CreateMeetingContainer.jsx
  src/components/createMeeting/TripPeriod.jsx
  src/components/postDetail/PostDetailImg.jsx
  src/pages/PostDetailPage.jsx
Labels: ⭐ 스타일

#224 [FEAT] 여행친구찾기 전체리스트 출력
  src/components/meetingList/MeetingListCard.jsx
  src/components/meetingList/MeetingListContainer.jsx
Labels: 🏆 기능구현

#225 [CD] 여행친구찾기 전체리스트 출력
  src/components/meetingList/MeetingListCard.jsx
  src/components/meetingList/MeetingListContainer.jsx
Labels: 🎬 배포

#230 [FEAT] 모집글 수정 페이지 기능 추가
  src/components/createMeeting/CreateMeetingContainer.jsx
  src/components/createMeeting/MeetingLocationSearch.jsx
  src/components/createMeeting/RoomCloseDateBox.jsx
  src/components/createMeeting/TripPeriod.jsx
  src/components/createMeeting/UpdateMeetingContainer.jsx
  src/components/createPost/CreatePostContainer.jsx
  src/components/createPost/CreatePostContent.jsx
  src/index.js
Labels: 🏆 기능구현

#232 [CD] 에러 수정
  src/components/createMeeting/CreateMeetingContainer.jsx
  src/components/createMeeting/MeetingLocationSearch.jsx
  src/components/createMeeting/RoomCloseDateBox.jsx
  src/components/createMeeting/TripPeriod.jsx
  src/components/createMeeting/UpdateMeetingContainer.jsx
  src/components/createPost/CreatePostContainer.jsx
  src/components/createPost/CreatePostContent.jsx
  src/components/meetingList/MeetingListCard.jsx
  src/index.js
Labels: 🐞오류, 🏆 기능구현, ⭐ 스타일, 🎬 배포

#237 [FEAT] 메인, 상세, 모집글조회 페이지 react-query 적용
  package.json
  src/components/main/HeartButton.jsx
  src/components/main/MainMenu.jsx
  src/components/main/MainPostCard.jsx
  src/components/main/MainPostList.jsx
  src/components/meetingList/MeetingListCard.jsx
  src/components/meetingList/MeetingListContainer.jsx
  src/components/postDetail/PostDetailContainer.jsx
  src/components/postDetail/PostDetailLike.jsx
  src/elements/HeartButton.jsx
  src/index.js
  yarn.lock
Labels: 🏆 기능구현

#238 [FEAT] 메인, 상세, 모집글조회 페이지 react-query 적용
  package.json
  src/components/main/HeartButton.jsx
  src/components/main/MainMenu.jsx
  src/components/main/MainPostCard.jsx
  src/components/main/MainPostList.jsx
  src/components/meetingList/MeetingListCard.jsx
  src/components/meetingList/MeetingListContainer.jsx
  src/components/postDetail/PostDetailContainer.jsx
  src/components/postDetail/PostDetailLike.jsx
  src/elements/HeartButton.jsx
  src/index.js
  yarn.lock
Labels: 🎬 배포

#239 [FEAT] 미팅리스트 카테고리 전체 추가 / tag 컨포넌트 모듈화
  src/components/createMeeting/CreateMeetingContainer.jsx
  src/components/createMeeting/UpdateMeetingContainer.jsx
  src/components/createPost/CreatePostContainer.jsx
  src/components/meetingList/MeetingListCard.jsx
  src/components/meetingList/MeetingListContainer.jsx
  src/elements/TagInput.jsx
  src/redux/modules/meetingSlice.js
  src/redux/modules/postSlice.js
  src/redux/modules/themeSlice.js
  src/redux/modules/userSlice.js
  src/redux/store.js
Labels: 🏆 기능구현

#241 [DOCS] 개발 타임라인 및 개발 기술 스택 업데이트
  README.md
Labels: 📝 문서화

#242 [SETTING] 반응형 작업
  README.md
  src/components/main/MainPostCard.jsx
  src/components/myProfile/MyPostList.jsx
  src/components/searchTag/SearchTagContainder.jsx
  src/global/GlobalHeader.jsx
  src/global/GlobalLayout.jsx
  src/index.js
  src/shared/Router.jsx
Labels: 🏆 기능구현, ⭐ 스타일

#243 [FEAT] 반응형 ::: 헤더, 마이페이지, 미팅리스트, 게시글등록
  src/components/createPost/CreatePostContainer.jsx
  src/components/createPost/CreatePostImage.jsx
  src/components/createPost/CreatePostImageCrop.jsx
  src/components/header/search/SearchContainer.jsx
  src/components/main/MainPostCard.jsx
  src/components/meetingList/MeetingListCard.jsx
  src/components/meetingList/MeetingListContainer.jsx
  src/components/myProfile/MyPostList.jsx
  src/components/myProfile/MyProfileContainer.jsx
  src/components/myProfile/UpdateMyProfile.jsx
  src/components/postDetail/PostDetailImg.jsx
  src/components/searchTag/SearchTagContainder.jsx
  src/components/updatePost/UpdatePostContainer.jsx
  src/elements/Button.jsx
  src/global/GlobalHeader.jsx
  src/global/GlobalLayout.jsx
  src/global/globalModal/Modal.jsx
  src/index.js
Labels: 🏆 기능구현, ⭐ 스타일

#244 [FEAT] 반응형 채팅페이지, 검색페이지 리액트 쿼리 변환
  src/components/chatting/Chat.jsx
  src/components/chatting/ChatList.jsx
  src/components/chatting/ChatName.jsx
  src/components/chatting/ChattingRoom.jsx
  src/components/chatting/MessageInput.jsx
  src/components/chatting/MessageList.jsx
  src/components/chatting/MessageWrite.jsx
  src/components/meetingList/MeetingListCard.jsx
  src/components/searchTag/SearchTagContainder.jsx
  src/pages/ChattingPage.jsx
Labels: 🏆 기능구현, ⭐ 스타일

#245 [CD] 반응형 작업 진행, 검색 상세 페이지 useQuery변환 외
  README.md
  src/components/chatting/Chat.jsx
  src/components/chatting/ChatList.jsx
  src/components/chatting/ChatName.jsx
  src/components/chatting/ChattingRoom.jsx
  src/components/chatting/MessageInput.jsx
  src/components/chatting/MessageList.jsx
  src/components/chatting/MessageWrite.jsx
  src/components/createPost/CreatePostContainer.jsx
  src/components/createPost/CreatePostImage.jsx
  src/components/createPost/CreatePostImageCrop.jsx
  src/components/header/search/SearchContainer.jsx
  src/components/main/MainPostCard.jsx
  src/components/meetingList/MeetingListCard.jsx
  src/components/meetingList/MeetingListContainer.jsx
  src/components/myProfile/MyPostList.jsx
  src/components/myProfile/MyProfileContainer.jsx
  src/components/myProfile/UpdateMyProfile.jsx
  src/components/postDetail/PostDetailImg.jsx
  src/components/searchTag/SearchTagContainder.jsx
  src/components/updatePost/UpdatePostContainer.jsx
  src/elements/Button.jsx
  src/global/GlobalHeader.jsx
  src/global/GlobalLayout.jsx
  src/global/globalModal/Modal.jsx
  src/index.js
  src/pages/ChattingPage.jsx
  src/shared/Router.jsx
Labels: 🏆 기능구현, ⭐ 스타일, 🎬 배포

#246 [FIX] 헤더 버튼 안눌리는 현상 해결
  src/components/header/search/SearchContainer.jsx
  src/components/meetingList/MeetingListContainer.jsx
  src/components/searchTag/SearchTagContainder.jsx
  src/global/GlobalHeader.jsx
Labels: 🐞오류

#248 [DOCS] 개발 타임라인 작성
  README.md
Labels: 📝 문서화

#249 [FEAT] 메인 페이지 게시글 무한스크롤 구현, 로딩&에러 컨포넌트 추가
  src/components/main/MainPostList.jsx
  src/elements/Error.jsx
  src/elements/Loading.jsx
Labels: 🏆 기능구현

#250 [CD] 메인페이지 무한스크롤 적용
  README.md
  src/components/main/MainPostList.jsx
  src/elements/Error.jsx
  src/elements/Loading.jsx
Labels: 🎬 배포

#251 [FEAT] 게시글 등록 이미지 최대사이즈 설정
  src/components/createPost/CreatePostImageCrop.jsx
Labels: 🏆 기능구현

#252 [CD] 게시글 등록 이미지 최대사이즈 설정
  src/components/createPost/CreatePostImageCrop.jsx
Labels: 🎬 배포

#254 [CD] 모집글 수정페이지- 유효성 검사, react-query 변환, 반응형
  src/components/chatting/MessageWrite.jsx
  src/components/createMeeting/CreateMeetingContainer.jsx
  src/components/createMeeting/KakaoMap.jsx
  src/components/createMeeting/MeetingLocationSearch.jsx
  src/components/createMeeting/RoomCloseDateBox.jsx
  src/components/createMeeting/ThemeSelect.jsx
  src/components/createMeeting/TripPeriod.jsx
  src/components/createMeeting/UpdateMeetingContainer.jsx
  src/components/meetingList/MeetingListCard.jsx
Labels: 🎬 배포

#255 [FEAT] 메인페이지 실시간, 추천순 무한스크롤 구현, 반응형 헤더 모바일 버전 사이즈 조절 외
  README.md
  src/components/header/search/SearchContainer.jsx
  src/components/main/MainContainer.jsx
  src/components/main/MainMenu.jsx
  src/components/main/MainPostCard.jsx
  src/components/main/MainPostList.jsx
  src/components/meetingList/MeetingListContainer.jsx
  src/elements/Error.jsx
  src/elements/HeartButton.jsx
  src/elements/Loading.jsx
  src/global/GlobalLayout.jsx
  src/pages/MainPage.jsx
  src/shared/Router.jsx
Labels: 🐞오류, 🏆 기능구현, ⭐ 스타일

#256 [CD] 메인페이지 실시간, 추천순 무한스크롤 구현, 반응형 헤더 모바일 버전 사이즈 조절 외
  README.md
  src/components/header/search/SearchContainer.jsx
  src/components/main/MainContainer.jsx
  src/components/main/MainMenu.jsx
  src/components/main/MainPostCard.jsx
  src/components/main/MainPostList.jsx
  src/components/meetingList/MeetingListContainer.jsx
  src/elements/Error.jsx
  src/elements/HeartButton.jsx
  src/elements/Loading.jsx
  src/global/GlobalLayout.jsx
  src/pages/MainPage.jsx
  src/shared/Router.jsx
Labels: 🎬 배포

#260 [FEAT] 게시글 등록 mutation설정
  src/components/createPost/CreatePostContainer.jsx
  src/components/main/MainPostList.jsx
  src/components/postDetail/PostDetailContainer.jsx
  src/index.js
Labels: 🏆 기능구현

#261 [CD] 게시글 등록 mutation설정
  src/components/createPost/CreatePostContainer.jsx
  src/components/main/MainPostList.jsx
  src/components/postDetail/PostDetailContainer.jsx
  src/index.js
Labels: 🎬 배포

#262 [FEAT] 게시글 등록 mutation설정 삭제
  src/components/createPost/CreatePostContainer.jsx
Labels: 🐞오류

#263 [CD] 게시글 등록 mutation설정 삭제
  src/components/createPost/CreatePostContainer.jsx
Labels: 🎬 배포

#265 [FEAT] 게시글 등록 이미지 리사이징 기능 추가 (#264)
  src/components/createPost/CreatePostImage.jsx
  src/components/myProfile/UpdateMyProfile.jsx
Labels: 🐞오류, 🏆 기능구현, 💦 테스트

#266 [CD] 게시글 등록 이미지 리사이징 기능 추가 (#264)
  src/components/createPost/CreatePostImage.jsx
  src/components/myProfile/UpdateMyProfile.jsx
Labels: 🎬 배포

#268 [CD] 채팅페이지 서버와 연결
  src/components/chatting/ChattingRoom.jsx
  src/components/chatting/Message.jsx
  src/components/chatting/MessageWrite.jsx
  src/components/createMeeting/CreateMeetingContainer.jsx
  src/components/meetingList/MeetingListCard.jsx
Labels: 🎬 배포

#269 [FEAT] 채팅페이지 서버랑 연결
  src/components/chatting/Chat.jsx
  src/components/chatting/ChatList.jsx
  src/components/chatting/ChattingRoom.jsx
  src/components/chatting/Message.jsx
  src/components/chatting/MessageList.jsx
Labels: 🏆 기능구현

#270 [FEAT] 게시글 등록 이미지리사이징 기능구현 (#264) / 개발타임라인 작성
  README.md
  docs/imageResizingSample.png
  src/components/createPost/CreatePostContainer.jsx
  src/components/createPost/CreatePostImage.jsx
  src/components/createPost/CreatePostImageCrop.jsx
  src/components/main/MainPostCard.jsx
  src/components/main/MainPostList.jsx
  src/elements/Error.jsx
  src/elements/Loading.jsx
Labels: 📝 문서화, 🏆 기능구현

#271 [CD] 게시글 등록 이미지리사이징 기능구현 (#264) / 무한스크롤 오류 해결 / 채팅기능구현(#259)
  README.md
  docs/imageResizingSample.png
  src/components/chatting/Chat.jsx
  src/components/chatting/ChatList.jsx
  src/components/chatting/ChattingRoom.jsx
  src/components/chatting/Message.jsx
  src/components/chatting/MessageList.jsx
  src/components/createPost/CreatePostContainer.jsx
  src/components/createPost/CreatePostImage.jsx
  src/components/createPost/CreatePostImageCrop.jsx
  src/components/main/MainPostCard.jsx
  src/components/main/MainPostList.jsx
  src/elements/Error.jsx
  src/elements/Loading.jsx
Labels: 🐞오류, 🏆 기능구현, ⭐ 스타일, 🎬 배포

#274 [FIX]채팅 실시간오류 해결
  src/components/chatting/ChatName.jsx
  src/components/chatting/ChattingRoom.jsx
  src/components/chatting/Message.jsx
  src/components/chatting/MessageList.jsx
  src/components/main/MainPostCard.jsx
  src/components/meetingList/MeetingListCard.jsx
  src/components/myProfile/UpdateMyProfile.jsx
  src/components/postDetail/PostDetailContainer.jsx
  src/components/postDetail/PostDetailLike.jsx
  src/index.js
Labels: 🐞오류

#279 [FEAT] 마이페이지 프로필 수정 기능구현(#278), 이미지리사이징 관련 리드미 작성중
  README.md
  docs/imageResizingSampleMobile.png
  src/components/createPost/CreatePostImageCrop.jsx
  src/components/login/KakaoLogin.jsx
  src/components/myProfile/UpdateMyProfile.jsx
Labels: 📝 문서화, 🏆 기능구현

#280 [FEAT] 마이페이지 프로필 수정 기능구현(#278), 이미지리사이징 관련 리드미 작성중
  README.md
  docs/imageResizingSampleMobile.png
  src/components/createPost/CreatePostImageCrop.jsx
  src/components/login/KakaoLogin.jsx
  src/components/myProfile/UpdateMyProfile.jsx
Labels: 🎬 배포

#284 [FEAT] 모달 모듈화/닫기 버튼, 검색어 에러 해결 외
  README.md
  src/components/createPost/CreatePostImageCrop.jsx
  src/components/header/search/SearchContainer.jsx
  src/elements/Info.jsx
  src/elements/Success.jsx
  src/elements/Warning.jsx
  src/global/GlobalStyle.jsx
  src/global/globalModal/Modal.jsx
  src/pages/NotFound.jsx
  src/shared/Router.jsx
Labels: 🐞오류, 📝 문서화, ⭐ 스타일

#286 [FEAT] 채팅창 단건조회, 삭제 추가
  src/components/chatting/Chat.jsx
  src/components/chatting/ChatList.jsx
  src/components/chatting/ChatName.jsx
  src/components/chatting/NoRoom.jsx
  src/components/createMeeting/CreateMeetingContainer.jsx
  src/components/createMeeting/TripPeopleCount.jsx
  src/components/meetingList/MeetingListCard.jsx
  src/components/postDetail/PostDetailContainer.jsx
Labels: 🏆 기능구현

#287 [FEAT] 무한스크롤 해결중, 검색상세페이지 테마 주석처리
  README.md
  src/components/createPost/CreatePostContainer.jsx
  src/components/main/MainPostList.jsx
  src/components/searchTag/SearchTagContainder.jsx
  src/index.js
Labels: 📝 문서화, 💦 테스트

#288 [CD] 채팅기능구현(삭제, 정보조회), 무한스크롤 해결중, 검색상세페이지 테마 주석처리
  README.md
  src/components/chatting/Chat.jsx
  src/components/chatting/ChatList.jsx
  src/components/chatting/ChatName.jsx
  src/components/chatting/NoRoom.jsx
  src/components/createMeeting/CreateMeetingContainer.jsx
  src/components/createMeeting/TripPeopleCount.jsx
  src/components/createPost/CreatePostContainer.jsx
  src/components/main/MainPostList.jsx
  src/components/meetingList/MeetingListCard.jsx
  src/components/postDetail/PostDetailContainer.jsx
  src/components/searchTag/SearchTagContainder.jsx
  src/index.js
Labels: 🎬 배포

#289 [FEAT] 연관게시글조회, 상세검색내용 없는 경우 메시지 출력, 메인무한스크롤 반영오류 해결
  src/components/main/MainPostList.jsx
  src/components/postDetail/PostDetailContainer.jsx
  src/components/postDetail/RelatedList.jsx
  src/components/searchTag/SearchTagContainder.jsx
Labels: 🐞오류, 🏆 기능구현

#290 [CD] 연관게시글조회, 상세검색내용 없는 경우 메시지 출력, 메인무한스크롤 반영오류 해결
  src/components/main/MainPostList.jsx
  src/components/postDetail/PostDetailContainer.jsx
  src/components/postDetail/RelatedList.jsx
  src/components/searchTag/SearchTagContainder.jsx
Labels: 🎬 배포

#293 [FEAT] 마이페이지 내 모집글 리스트 조회 기능 구현, 슬라이드 모듈화진행중
  src/components/createPost/CreatePostContainer.jsx
  src/components/meetingList/MeetingListCard.jsx
  src/components/myProfile/MyMeetingList.jsx
  src/components/myProfile/MyProfileContainer.jsx
  src/elements/Slider.jsx
Labels: 🏆 기능구현

#294 [FEAT]Modal 모듈화해서 적용, 모집글 생성페이지 유효성검사 추가, 모집글 수정페이지 수정
  src/components/chatting/ChatList.jsx
  src/components/chatting/ChatName.jsx
  src/components/chatting/ChattingRoom.jsx
  src/components/chatting/Message.jsx
  src/components/chatting/MessageInput.jsx
  src/components/chatting/MessageList.jsx
  src/components/chatting/NoRoom.jsx
  src/components/createMeeting/CreateMeetingContainer.jsx
  src/components/createMeeting/MeetingLocationSearch.jsx
  src/components/createMeeting/RoomCloseDateBox.jsx
  src/components/createMeeting/TripPeopleCount.jsx
  src/components/createMeeting/UpdateMeetingContainer.jsx
  src/components/createPost/CreatePostContainer.jsx
  src/components/createPost/CreatePostImageCrop.jsx
  src/components/main/MainPostCard.jsx
  src/components/meetingList/MeetingListCard.jsx
  src/components/postDetail/PostDetailLike.jsx
  src/components/postDetail/PostDetailUser.jsx
  src/components/searchTag/SearchTagContainder.jsx
  src/components/updatePost/UpdatePostContainer.jsx
  src/global/globalModal/AlertModal.jsx
  src/global/globalModal/CofirmModal.jsx
  src/global/globalModal/Modal.jsx
Labels: 🏆 기능구현

#295 [CD] Modal 모듈화해서 적용, 마이페이지에 내가 작성한 모집글 내용 추가
  src/components/chatting/ChatList.jsx
  src/components/chatting/ChatName.jsx
  src/components/chatting/ChattingRoom.jsx
  src/components/chatting/Message.jsx
  src/components/chatting/MessageInput.jsx
  src/components/chatting/MessageList.jsx
  src/components/chatting/NoRoom.jsx
  src/components/createMeeting/CreateMeetingContainer.jsx
  src/components/createMeeting/MeetingLocationSearch.jsx
  src/components/createMeeting/RoomCloseDateBox.jsx
  src/components/createMeeting/TripPeopleCount.jsx
  src/components/createMeeting/UpdateMeetingContainer.jsx
  src/components/createPost/CreatePostContainer.jsx
  src/components/createPost/CreatePostImageCrop.jsx
  src/components/main/MainPostCard.jsx
  src/components/meetingList/MeetingListCard.jsx
  src/components/myProfile/MyMeetingList.jsx
  src/components/myProfile/MyProfileContainer.jsx
  src/components/postDetail/PostDetailLike.jsx
  src/components/postDetail/PostDetailUser.jsx
  src/components/searchTag/SearchTagContainder.jsx
  src/components/updatePost/UpdatePostContainer.jsx
  src/elements/Slider.jsx
  src/global/globalModal/AlertModal.jsx
  src/global/globalModal/CofirmModal.jsx
  src/global/globalModal/Modal.jsx
Labels: 🎬 배포

#296 [FEAT] 슬라이드 커스터마이징, 메인 슬라이드 추가
  src/assets/arrowNext.svg
  src/assets/arrowPrev.svg
  src/assets/defaultProfileImage.svg
  src/components/main/MainBanner.jsx
  src/components/main/MainContainer.jsx
  src/components/main/MainPostList.jsx
  src/components/myProfile/MyMeetingList.jsx
  src/components/postDetail/PostDetailImg.jsx
  src/elements/Slider.jsx
  src/elements/slider/slick-theme.css
  src/elements/slider/slick.css
  src/pages/MainPage.jsx
  src/shared/Router.jsx
Labels: 🏆 기능구현, ⭐ 스타일

#297 [STYLE] 로그인 모달 스타일 수정
  src/assets/facebook.svg
  src/assets/kakao.svg
  src/assets/naver.svg
  src/assets/notPrepare.svg
  src/assets/raidhoLogo.svg
  src/components/login/LoginContainer.jsx
Labels: ⭐ 스타일

#298 [CD] 슬라이드 커스터마이징, 로그인 모달 스타일 수정, 매인배너 세팅
  src/assets/arrowNext.svg
  src/assets/arrowPrev.svg
  src/assets/defaultProfileImage.svg
  src/assets/facebook.svg
  src/assets/kakao.svg
  src/assets/naver.svg
  src/assets/notPrepare.svg
  src/assets/raidhoLogo.svg
  src/components/login/LoginContainer.jsx
  src/components/main/MainBanner.jsx
  src/components/main/MainContainer.jsx
  src/components/main/MainPostList.jsx
  src/components/myProfile/MyMeetingList.jsx
  src/components/postDetail/PostDetailImg.jsx
  src/elements/Slider.jsx
  src/elements/slider/slick-theme.css
  src/elements/slider/slick.css
  src/pages/MainPage.jsx
  src/shared/Router.jsx
Labels: 🎬 배포

#299 [FIX] 메인 배너 레이아웃 수정
  src/components/main/MainBanner.jsx
  src/pages/MainPage.jsx
  src/shared/Router.jsx
Labels: ⭐ 스타일

#300 [CD] 메인 배너 레이아웃 수정
  src/components/main/MainBanner.jsx
  src/pages/MainPage.jsx
  src/shared/Router.jsx
Labels: 🎬 배포

#301 [FEAT] 헤더 스타일 적용(데스크탑)
  src/assets/header/add.svg
  src/assets/header/chat.svg
  src/assets/header/meeting.svg
  src/assets/header/post.svg
  src/assets/header/togglebox.svg
  src/assets/search.svg
  src/components/header/HeaderContainer.jsx
  src/components/header/HeaderRightMenu.jsx
  src/components/header/search/SearchContainer.jsx
  src/components/header/toggle/ToggleBox.jsx
  src/components/login/LoginContainer.jsx
  src/components/main/MainBanner.jsx
  src/elements/Button.jsx
  src/elements/Input.jsx
  src/pages/MainPage.jsx
  src/shared/Router.jsx
Labels: 🏆 기능구현, ⭐ 스타일

#302 [CD] 헤더 스타일 변경 적용(데스크탑버전)
  src/assets/header/add.svg
  src/assets/header/chat.svg
  src/assets/header/meeting.svg
  src/assets/header/post.svg
  src/assets/header/togglebox.svg
  src/assets/search.svg
  src/components/header/HeaderContainer.jsx
  src/components/header/HeaderRightMenu.jsx
  src/components/header/search/SearchContainer.jsx
  src/components/header/toggle/ToggleBox.jsx
  src/components/login/LoginContainer.jsx
  src/components/main/MainBanner.jsx
  src/elements/Button.jsx
  src/elements/Input.jsx
  src/pages/MainPage.jsx
  src/shared/Router.jsx
Labels: ⭐ 스타일, 🎬 배포

#303 [FIX] 로그인 시 화면에 적용이 바로 안되는 현상
  src/components/header/HeaderContainer.jsx
  src/components/header/HeaderRightMenu.jsx
Labels: 🐞오류

#304 [CD] 로그인 시 화면에 적용이 바로 안되는 현상
  src/components/header/HeaderContainer.jsx
  src/components/header/HeaderRightMenu.jsx
Labels: 🎬 배포

#305 [STYLE] 자랑글상세페이지 스타일 변경, 메인페이지 스크롤 업 버튼 추가
  src/components/createMeeting/CreateMeetingContainer.jsx
  src/components/createMeeting/MeetingLocationSearch.jsx
  src/components/createMeeting/RoomCloseDateBox.jsx
  src/components/createMeeting/TripPeopleCount.jsx
  src/components/createMeeting/TripPeriod.jsx
  src/components/createMeeting/UpdateMeetingContainer.jsx
  src/components/meetingList/MeetingListCard.jsx
  src/components/postDetail/PostDetailContainer.jsx
  src/components/postDetail/PostDetailImg.jsx
  src/components/postDetail/PostDetailTagList.jsx
  src/components/postDetail/PostDetailUser.jsx
  src/global/GlobalLayout.jsx
  src/pages/MainPage.jsx
  src/pages/PostDetailPage.jsx
Labels: 🏆 기능구현, ⭐ 스타일

#306 [CD] 모집글 수정페이지 스타일 수정, 메인페이지 스크롤업버튼 추가
  src/components/createMeeting/CreateMeetingContainer.jsx
  src/components/createMeeting/MeetingLocationSearch.jsx
  src/components/createMeeting/RoomCloseDateBox.jsx
  src/components/createMeeting/TripPeopleCount.jsx
  src/components/createMeeting/TripPeriod.jsx
  src/components/createMeeting/UpdateMeetingContainer.jsx
  src/components/meetingList/MeetingListCard.jsx
  src/components/postDetail/PostDetailContainer.jsx
  src/components/postDetail/PostDetailImg.jsx
  src/components/postDetail/PostDetailTagList.jsx
  src/components/postDetail/PostDetailUser.jsx
  src/global/GlobalLayout.jsx
  src/pages/MainPage.jsx
  src/pages/PostDetailPage.jsx
Labels: 🎬 배포

#307 [FEAT] 게시글 상세 레이아웃 수정
  src/components/postDetail/PostDetailContainer.jsx
  src/components/postDetail/PostDetailImg.jsx
  src/components/postDetail/PostDetailUser.jsx
Labels: ⭐ 스타일

#308 [CD] 게시글 상세 레이아웃 수정
  src/components/postDetail/PostDetailContainer.jsx
  src/components/postDetail/PostDetailImg.jsx
  src/components/postDetail/PostDetailUser.jsx
Labels: ⭐ 스타일, 🎬 배포

#310 [CD] 웹폰트 적용
  src/components/postDetail/PostDetailUser.jsx
  src/global/GlobalStyle.jsx
Labels: 🎬 배포

#311 [FEAT] 디자인 적용 ::: 마이페이지, 미팅리스트, 여행후기등록, 헤더 토글 수정, not found 페이지 외
  src/assets/iconDarkMode.svg
  src/assets/iconError.svg
  src/assets/iconLightMode.svg
  src/components/createPost/CreatePostContainer.jsx
  src/components/createPost/CreatePostImage.jsx
  src/components/createPost/CreatePostImageCrop.jsx
  src/components/header/toggle/ToggleBox.jsx
  src/components/meetingList/MeetingListCard.jsx
  src/components/meetingList/MeetingListContainer.jsx
  src/components/myProfile/MyProfileContainer.jsx
  src/elements/Button.jsx
  src/elements/ContentTextArea.jsx
  src/elements/TagInput.jsx
  src/global/GlobalLayout.jsx
  src/global/GlobalStyle.jsx
  src/global/globalModal/Modal.jsx
  src/pages/NotFound.jsx
Labels: 🏆 기능구현, ⭐ 스타일

#312 [CD] 디자인 적용 ::: 마이페이지, 미팅리스트, 여행후기등록, 헤더 토글 수정 외
  src/assets/iconDarkMode.svg
  src/assets/iconError.svg
  src/assets/iconLightMode.svg
  src/components/createPost/CreatePostContainer.jsx
  src/components/createPost/CreatePostImage.jsx
  src/components/createPost/CreatePostImageCrop.jsx
  src/components/header/toggle/ToggleBox.jsx
  src/components/meetingList/MeetingListCard.jsx
  src/components/meetingList/MeetingListContainer.jsx
  src/components/myProfile/MyProfileContainer.jsx
  src/elements/Button.jsx
  src/elements/ContentTextArea.jsx
  src/elements/TagInput.jsx
  src/global/GlobalLayout.jsx
  src/global/GlobalStyle.jsx
  src/global/globalModal/Modal.jsx
  src/pages/NotFound.jsx
Labels: 🎬 배포

#313 [FIX] 헤더 z-index 수정
  src/components/header/HeaderContainer.jsx
  src/components/header/toggle/ToggleBox.jsx
  src/components/meetingList/MeetingListCard.jsx
Labels: ⭐ 스타일

#314 [STYLE] 여행후기글 상세페이지 스타일 수정
  src/components/chatting/ChattingRoom.jsx
  src/components/chatting/MessageList.jsx
  src/components/meetingList/MeetingListCard.jsx
  src/components/postDetail/PostDetailContainer.jsx
  src/components/postDetail/PostDetailDate.jsx
  src/components/postDetail/PostDetailLike.jsx
  src/components/postDetail/PostDetailUser.jsx
Labels: ⭐ 스타일

#315 [CD] db에 쌓인 채팅 못가져오던 오류 해결, 여행후기글 상세페이지 스타일 수정
  src/components/chatting/ChattingRoom.jsx
  src/components/chatting/MessageList.jsx
  src/components/header/HeaderContainer.jsx
  src/components/header/toggle/ToggleBox.jsx
  src/components/meetingList/MeetingListCard.jsx
  src/components/postDetail/PostDetailContainer.jsx
  src/components/postDetail/PostDetailDate.jsx
  src/components/postDetail/PostDetailLike.jsx
  src/components/postDetail/PostDetailUser.jsx
Labels: ⭐ 스타일, 🎬 배포

#316 [FEAT] 디자인 적용 ::: 메인, 헤더(모바일), 마이페이지 오류해결
  src/App.js
  src/assets/header/add.svg
  src/assets/header/toggleBoxDark.svg
  src/assets/header/toggleBoxLight.svg
  src/assets/header/togglebox.svg
  src/components/header/HeaderContainer.jsx
  src/components/header/HeaderRightMenu.jsx
  src/components/header/search/SearchContainer.jsx
  src/components/header/toggle/ToggleBox.jsx
  src/components/main/MainPostCard.jsx
  src/components/main/MainPostList.jsx
  src/components/myProfile/MyMeetingList.jsx
  src/components/myProfile/MyProfileContainer.jsx
  src/elements/Button.jsx
  src/global/GlobalLayout.jsx
  src/pages/MainPage.jsx
  src/shared/Router.jsx
Labels: 🐞오류, ⭐ 스타일

#317 [CD] 디자인 적용 ::: 메인, 헤더(모바일), 마이페이지 오류해결
  src/App.js
  src/assets/header/add.svg
  src/assets/header/toggleBoxDark.svg
  src/assets/header/toggleBoxLight.svg
  src/assets/header/togglebox.svg
  src/components/header/HeaderContainer.jsx
  src/components/header/HeaderRightMenu.jsx
  src/components/header/search/SearchContainer.jsx
  src/components/header/toggle/ToggleBox.jsx
  src/components/main/MainPostCard.jsx
  src/components/main/MainPostList.jsx
  src/components/myProfile/MyMeetingList.jsx
  src/components/myProfile/MyProfileContainer.jsx
  src/elements/Button.jsx
  src/global/GlobalLayout.jsx
  src/pages/MainPage.jsx
  src/shared/Router.jsx
Labels: 🎬 배포

#322 [CD] 주석처리
  src/components/chatting/ChatList.jsx
  src/components/chatting/ChatName.jsx
Labels: 🎬 배포
